// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: ops.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSupportedDeploymentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSupportedDeploymentsReq) Reset() {
	*x = ListSupportedDeploymentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSupportedDeploymentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedDeploymentsReq) ProtoMessage() {}

func (x *ListSupportedDeploymentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedDeploymentsReq.ProtoReflect.Descriptor instead.
func (*ListSupportedDeploymentsReq) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{0}
}

type ListSupportedDeploymentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployment []string `protobuf:"bytes,1,rep,name=deployment,proto3" json:"deployment,omitempty"`
}

func (x *ListSupportedDeploymentsResp) Reset() {
	*x = ListSupportedDeploymentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSupportedDeploymentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedDeploymentsResp) ProtoMessage() {}

func (x *ListSupportedDeploymentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedDeploymentsResp.ProtoReflect.Descriptor instead.
func (*ListSupportedDeploymentsResp) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{1}
}

func (x *ListSupportedDeploymentsResp) GetDeployment() []string {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type GetDeploymentStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Release   string `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *GetDeploymentStatusReq) Reset() {
	*x = GetDeploymentStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeploymentStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusReq) ProtoMessage() {}

func (x *GetDeploymentStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusReq.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusReq) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeploymentStatusReq) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *GetDeploymentStatusReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetDeploymentStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status            string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FirstDeployed     string `protobuf:"bytes,2,opt,name=firstDeployed,proto3" json:"firstDeployed,omitempty"`
	LastDeployed      string `protobuf:"bytes,3,opt,name=lastDeployed,proto3" json:"lastDeployed,omitempty"`
	StatusDescription string `protobuf:"bytes,4,opt,name=statusDescription,proto3" json:"statusDescription,omitempty"`
}

func (x *GetDeploymentStatusResp) Reset() {
	*x = GetDeploymentStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ops_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeploymentStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResp) ProtoMessage() {}

func (x *GetDeploymentStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResp.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResp) Descriptor() ([]byte, []int) {
	return file_ops_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeploymentStatusResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDeploymentStatusResp) GetFirstDeployed() string {
	if x != nil {
		return x.FirstDeployed
	}
	return ""
}

func (x *GetDeploymentStatusResp) GetLastDeployed() string {
	if x != nil {
		return x.LastDeployed
	}
	return ""
}

func (x *GetDeploymentStatusResp) GetStatusDescription() string {
	if x != nil {
		return x.StatusDescription
	}
	return ""
}

var File_ops_proto protoreflect.FileDescriptor

var file_ops_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x70, 0x73,
	0x22, 0x1d, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22,
	0x3e, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x50, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0xa9, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6c,
	0x61, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xbc, 0x01,
	0x0a, 0x03, 0x4f, 0x70, 0x73, 0x12, 0x61, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x20, 0x2e, 0x6f, 0x70, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6f, 0x70, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1b, 0x2e, 0x6f, 0x70, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6f,
	0x70, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x76, 0x69, 0x73,
	0x52, 0x61, 0x79, 0x4d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2d, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ops_proto_rawDescOnce sync.Once
	file_ops_proto_rawDescData = file_ops_proto_rawDesc
)

func file_ops_proto_rawDescGZIP() []byte {
	file_ops_proto_rawDescOnce.Do(func() {
		file_ops_proto_rawDescData = protoimpl.X.CompressGZIP(file_ops_proto_rawDescData)
	})
	return file_ops_proto_rawDescData
}

var file_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ops_proto_goTypes = []interface{}{
	(*ListSupportedDeploymentsReq)(nil),  // 0: ops.ListSupportedDeploymentsReq
	(*ListSupportedDeploymentsResp)(nil), // 1: ops.ListSupportedDeploymentsResp
	(*GetDeploymentStatusReq)(nil),       // 2: ops.GetDeploymentStatusReq
	(*GetDeploymentStatusResp)(nil),      // 3: ops.GetDeploymentStatusResp
}
var file_ops_proto_depIdxs = []int32{
	0, // 0: ops.Ops.ListSupportedDeployments:input_type -> ops.ListSupportedDeploymentsReq
	2, // 1: ops.Ops.GetDeploymentStatus:input_type -> ops.GetDeploymentStatusReq
	1, // 2: ops.Ops.ListSupportedDeployments:output_type -> ops.ListSupportedDeploymentsResp
	3, // 3: ops.Ops.GetDeploymentStatus:output_type -> ops.GetDeploymentStatusResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ops_proto_init() }
func file_ops_proto_init() {
	if File_ops_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ops_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSupportedDeploymentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSupportedDeploymentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeploymentStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ops_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeploymentStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ops_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ops_proto_goTypes,
		DependencyIndexes: file_ops_proto_depIdxs,
		MessageInfos:      file_ops_proto_msgTypes,
	}.Build()
	File_ops_proto = out.File
	file_ops_proto_rawDesc = nil
	file_ops_proto_goTypes = nil
	file_ops_proto_depIdxs = nil
}
