name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.1"

      - name: Verify dependencies
        run: go mod verify

      - name: Try build
        run: |
          go build -v ./cmd/server

      - name: Vet codebase
        run: go vet ./...

      - name: Run golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Setup bufbuild
        uses: bufbuild/buf-setup-action@v1.17.0

      - name: Run protobuf lint
        run: buf lint
        working-directory: ./proto
